FROM ruby:3.1.2

RUN apt-get update -qq \
  && apt-get install -y wget curl vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
ENV EDITOR=vim

ARG GID=1000
RUN groupadd --gid ${GID} rails
ARG UID=1000
RUN useradd -m --shell /bin/bash --uid ${UID} --gid ${GID} rails

ARG WORKDIR=/app
RUN mkdir ${WORKDIR} && chown rails:rails ${WORKDIR}
WORKDIR ${WORKDIR}

USER rails

ARG BUNDLE_PATH=/app/vendor/bundle
RUN mkdir -p ${BUNDLE_PATH}
ENV BUNDLE_PATH=${BUNDLE_PATH}
